language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - npm install -g mocha grunt grunt-cli
  - npm install
  - grunt build
  - grunt build-test
script:
  - grunt test
notifications:
  email: false
sudo: false
addons:
  code_climate:
    repo_token: 22ddde49b96cd7032e77bbac8ac2ed740993c876f50eb7d4eb702fcb80b1748e