language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - npm install
  - npm install -g mocha grunt grunt-cli
script:
  - grunt build-test
  - grunt test
notifications:
  email: false
sudo: false